name: my_secure_file_transfer

services:
  server:
    image: msft_server
    build:
      context: .
      dockerfile: ./env/server/server.Dockerfile
    ports:
      - "4444:4444"
    networks:
      static_network:
        ipv4_address: 10.5.0.10
    volumes:
      - ./env/server/log:/var/log/server

  client:
    image: msft_client
    build:
      context: .
      dockerfile: ./env/client/client.Dockerfile
    networks:
      static_network:
        ipv4_address: 10.5.0.11
    volumes:
      - ./env/client/log:/var/log/client
      - ./env/client/tests/:/opt/client


networks:
  static_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1
